# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1285792839);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1285792570);
user_pref("app.update.lastUpdateTime.microsummary-generator-update-timer", 1285598733);
user_pref("app.update.lastUpdateTime.places-maintenance-timer", 1285792929);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1285873640);
user_pref("browser.migration.version", 1);
user_pref("browser.places.importBookmarksHTML", false);
user_pref("browser.places.smartBookmarksVersion", 2);
user_pref("browser.startup.homepage_override.mstone", "rv:1.9.2.8");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("extensions.enabledItems", "langpack-en-GB@firefox-3.6.ubuntu.com:3.6,ubufox@ubuntu.com:0.9rc2,langpack-en-AU@firefox-3.6.ubuntu.com:3.6,langpack-en-CA@firefox-3.6.ubuntu.com:3.6,langpack-en@firefox-3.6.ubuntu.com:3.6,{972ce4c6-7e08-4474-a285-3208198ce6fd}:3.6.10");
user_pref("extensions.lastAppVersion", "3.6.10");
user_pref("extensions.newAddons", "langpack-en@firefox-3.6.ubuntu.com,langpack-en-CA@firefox-3.6.ubuntu.com,langpack-en-AU@firefox-3.6.ubuntu.com");
user_pref("extensions.update.notifyUser", false);
user_pref("idle.lastDailyNotification", 1285792298);
user_pref("intl.charsetmenu.browser.cache", "us-ascii, ISO-8859-1, UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("places.last_vacuum", 1285598606);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("security.warn_viewing_mixed", false);
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1285981347);
