#!/usr/bin/env python
import sys
from bitk import *

if '-h' in sys.argv:
	print "It does the job"
	sys.exit()



seq = sys.argv[1]

output = aln2vissa(seq)

outfile = open( seq[:-3] + 'vissa.aln', 'w')
outfile.write(output)
outfile.close()

