#! /usr/bin/env python 
###################################
#    Davi Ortega 4/8/2011 
###################################
import sys

if '-h' in sys.argv:
	print "Verify if there is any duplicates in fasta. No actions is taken."
	sys.exit()

filein = open(sys.argv[1],'r')

tag_list = []
dup = 0

for line in filein:
	if '>' in line:
		tag = line.split('>')[1]
		if tag in tag_list:
			print tag
			dup += 1
		else:
			tag_list.append(tag)

print 'There was ' + str(dup) + ' duplicates.'
	

