#! /usr/bin/env python 
###################################
#    Davi Ortega 8/22/2012 
###################################
import bitk
import sys
if '-h' in sys.argv:
	print 'Insert info in tag\nSintaxe: IIintag fasta_file.fa N info\n\tN is the position of info in tag fields (separated by "-"), 0 for last position\n\tinfo is any string to be placed in all tags in fastafile.fa\n\n-removelast remove the last field\n-subst Changes the Nth field info to the new info'
	sys.exit()

seq_dic, seq_list = bitk.fastareader(sys.argv[1])

output = ''

if '-removelast' in sys.argv:
	for tag in seq_list:
		new_tag = '-'.join(tag.split('-')[:-1])
		output += '>' + new_tag + '\n' + seq_dic[tag] + '\n'
	outfile = open(sys.argv[1][:-2] + 'IIintag_removelast.fa', 'w')
	outfile.write(output)
	outfile.close()
	print 'Done'
	sys.exit()
else:
	N = int(sys.argv[2])
	info = sys.argv[3]
	for tag in seq_list:
		if '-subst' not in sys.argv:
			new_tag = '-'.join(tag.split('-')[:N]) + '-' + info + '-' + '-'.join(tag.split('-')[N:])
		else:
			new_tag = '-'.join(tag.split('-')[:N-1]) + '-' + info + '-' + '-'.join(tag.split('-')[N:])
		if new_tag[-1] == '-':
			new_tag = new_tag[:-1]
		output += '>' + new_tag + '\n' + seq_dic[tag] + '\n'
	outfile = open(sys.argv[1][:-2] + 'IIintag.fa', 'w')
        outfile.write(output)
        outfile.close()
        print 'Done'
        sys.exit()

