#!/usr/bin/env python
from os import *
import os
import sys

if '-h' in sys.argv:
	print 'prepare every cluster in a different file in a fasta format, put them in one directory and run profmatch'

old_files = listdir(getcwd())
files = []
for aln in old_files:
	files.append(aln)

if 'profmatch' in files:
	files.remove('profmatch')
n = 1
for aln in files:
	os.system('ginsi ' + aln + ' > ' 'Profile' + str(n) +'.fa')
	n = n + 1

new_files = listdir(getcwd())

#if 'profmatch' in new_files:
#	new_files.remove('profmatch')

for aln in old_files:
	new_files.remove(aln)

list = range(len(new_files)-2)

print old_files
print new_files
print list

os.system('mafft-profile Profile1.fa Profile2.fa > Profile_0.fa')

for k in list:
	os.system('mafft-profile Profile_' + str(k) +'.fa Profile' + str(k+3) + '.fa > Profile_' + str(k+1) + '.fa')

os.system('cp Profile_' + str(list[-1]+1) + '.fa Profile.final.fa')
os.system('rm Profile_*')
		
print 'Done'

