#!/usr/bin/env python
import os
import sys
from bitk import *
from os import listdir
from os import getcwd

if '-h' in sys.argv:
	print 'prepare every cluster in a different file in a fasta format, put them in one directory and run profmatch'


if '-ng' in sys.argv:
	ng = 1
else:
	ng = 0

#program = 'clustalw'
#if 'fa' in sys.argv:
#	program = 'ginsi'
#if '-c' in sys.argv:
#	prof = 'clustaw'
#if '-f' in sys.argv:
#	prof = 'mafft'


old_files = listdir(getcwd())
files = []
for aln in old_files:
	files.append(aln)

if 'profmatch' in files:
	files.remove('profmatch')

alnprog = 'ginsi'
profprog = 'mafft'

if '-aln' in sys.argv:
	tag = 'pureclustalw'
	new_files = []
	for seq in files:
		output = fastareader(seq)
		if ng == 1:
			output = nogaps(output)
		output = alnwriter(output)
		outfile = open(seq[:-2] + 'aln', 'w')
		outfile.write(output)
		outfile.close()
		new_files.append(seq)
		os.system('clustalw -infile=' + seq + ' -outfile=' + seq[:-2] + 'profile.aln') 
	profprog = 'clustalw'
else:
	tag = 'puremafft'
	for aln in files:
		os.system('ginsi ' + aln + ' > ' + aln[:-2] + 'profile.fa')
#	new_files = listdir(getcwd())
	files = []
	for file in listdir(getcwd()):
		if file.find('.profile.') != -1:
			files.append(file)
	if '-c' in sys.argv:
		tag = 'mafft-clustalw'
		profprog = 'clustalw'
		for aln in files:
			os.system('fa2aln ' + aln)
#		new_files = listdir(getcwd())
		files = []
		for file in listdir(getcwd()):
			if file.find('.profile.aln') != -1:
				files.append(file)
		
new_files = files


#if 'profmatch' in new_files:
#	new_files.remove('profmatch')

#for aln in old_files:
#	new_files.remove(aln)

list = range(2,len(new_files))

#print old_files
#print new_files
#print list
if profprog == 'mafft':
	os.system('mafft-profile ' + new_files[0] + ' ' + new_files[1] + ' > Profile.tmp1.fa')
	for seq_num in list:
		os.system('mafft-profile Profile.tmp'+ str(seq_num-1)+'.fa ' +  new_files[seq_num] + ' > Profile.tmp'+ str(seq_num) +'.fa')
	os.system('cp Profile.tmp'+str(list[-1])+'.fa Profile.Final.' + tag + '.fa')
	os.system('rm Profile.tmp*')

if profprog == 'clustalw':
	os.system('clustalw -Profile1=' + new_files[0] + ' -Profile2=' + new_files[1] + ' -outfile=Profile.tmp1.aln')
	for seq_num in list:
		os.system('clustalw -Profile1=Profile.tmp'+ str(seq_num-1)+'.aln -Profile2='+ new_files[seq_num] + ' -outfile=Profile.tmp'+ str(seq_num)+'.aln')
	os.system('cp Profile.tmp'+ str(list[-1]) +'.aln Profile.Final.' + tag + '.aln')
	os.system('rm *dnd')
	os.system('rm Profile.tmp*')
		
print 'Done'

