#! /usr/bin/env python
import sys
import datetime

if '-h' in sys.argv:
	print "This program writes a small introduction to build a new executable python program\n\
	Sintax: start_py filename module1 module2 module3 ... (-help) to include help section"
	sys.exit()

if len(sys.argv) < 2 or '-h' in sys.argv:
	eval('info(startpy)')
filename = './' + sys.argv[1]
t = datetime.date.today().timetuple()
print filename
d = datetime.date.today().timetuple()
output = '#! /usr/bin/env python \n###################################\n#    Davi Ortega ' + str(t[1]) + '/' + str(t[2]) + '/' + str(t[0]) +' \n###################################\n'
for modules in sys.argv[2:]:
	if modules != '-help':
		output += 'import ' + modules +'\n'

if '-help' in sys.argv:
	output += "if '-h' in sys.argv:\n\tprint 'put your explanation here'\n\tsys.exit()\n"

datafile = open(filename,'w')
datafile.write(output)
datafile.close()
print 'File Created'
