#! /usr/bin/env python 
###################################
##    Davi Ortega                ##
###################################
import sys

if '-h' in sys.argv:
	print 'Uses Kristin\'s table to associate organism id to organism name.\n\n\tSintaxe: python getname.py file.list table.list'
	sys.exit()

listfile = open(sys.argv[1],'r')

mylist = []
for line in listfile:
	mylist.append(line.replace('\n',''))

print mylist

listfile.close()

tablefile = open(sys.argv[2],'r')

output = ''
for line in tablefile:
	orgnID = line.split('\t')[1]
	if orgnID in mylist:
		output += line.split('\t')[2] + '\n'

tablefile.close()

datafile = open(sys.argv[1][:-4] + 'name.list', 'w')
datafile.write(output)
datafile.close()



