#!/usr/bin/env python
import fileinput
from bitk import *
import sys

if '-h' in sys.argv or len(sys.argv) == 1:
	print 'Sequence in clustal format. \n \
	A table will be generated (dic_aln2phy.dat) and it can be used with the output tree to replace the taxon names using rectreetaxon\n' 
	sys.exit()

seq_dic = alnreader(sys.argv[1])

#print seq_dic




output = ''
seq_count = 0
dic = ''

for k, v in seq_dic.iteritems():
	if k != '':
		#print k
		if '/' in k:
			k = k[:k.find('/')]
		#print k
		kp = k.replace('_','')
		#print kp
		dic = dic + kp + ';' + k + '\n'
		#print '\n'
		output = output + kp + ' ' * (30 - len(kp)) + v + '\n'
		seq_count = seq_count + 1
		size = len(v)

output = '    ' + str(seq_count) + '     ' + str(size) + '\n' + output

#output = output.replace('_', '')


outfile = open(sys.argv[1][:-3] + 'phy', 'w')
outfile.write(output)
outfile.close()

outfile = open('dic_aln2phy.dat', 'w')
outfile.write(dic)
outfile.close()


print 'Done'


