#! /usr/bin/env python 
###################################
#    Davi Ortega 12/10/2014 
###################################
import bitk
import sys
import glob
if '-h' in sys.argv:
	print 'put your explanation here'
	sys.exit()




files = glob.glob(str(sys.argv[1]))

for F in files:
	aseqs = []
	print F
	seq_dic, seq_list = bitk.fastareader(F)
#	try:
#		N = int(sys.argv[2]) + 1
#	except:
#		N = 1

	for line in seq_list:
		aseqs.append(line)
		
	print aseqs
	A = bitk.aseq2bitktaglist(aseqs)

	output = ''
	nodeal = ''

	for aseq in aseqs:
		for tag in A[aseq]:
			if tag != 'None':
				output += '>' + tag + '\n' + seq_dic[aseq] + '\n'
			else:
				nodeal += '>' + aseq + '\n' + seq_dic[aseq] + '\n'
			print aseq + '\t' + tag

	with open(F[:-3] + '.bitktags.fa', 'w') as f:
		f.write(output)
	
	with open(F[:-3] + '.bitktags_nodeal.fa', 'w') as f:
	        f.write(nodeal)

