#!/usr/bin/env python
# 
import fileinput
import bitk
import sys
import json

if '-h' in sys.argv:
	print "Concatenates sequences in fa format:\n \
		Sintaxe: concatbyorganism left_seq.fa right_seq.fa (same organism)\n \
		Options: -n N   - Concat only if it is N genes up or downstream \n \
				 -ext extension  - include extension in outputfilename"
	sys.exit()


if '-ext' in sys.argv:
	ext = "." + sys.argv[sys.argv.index('-ext') + 1]
else:
	ext = ''

if '-n' in sys.argv:
	N = int(sys.argv[sys.argv.index('-n') + 1])

sequences1 = sys.argv[1]
sequences2 = sys.argv[2]

#print seq_seq
seq1_dic, seq1_list = bitk.fastareader(sequences1)
seq2_dic, seq2_list = bitk.fastareader(sequences2)

allseqs = seq1_list + seq2_list

#Parsing the AC from the list

AC_list = []
ac2tag = {}
tag2ac = {}

for tag in allseqs:
	ac = bitk.xtractAC(tag)
	if ac != 0:
		AC_list.append(ac)
		ac2tag[ac] = tag
		tag2ac[tag] = ac

mist22 = bitk.get_mist22_client()

print AC_list 

cards = mist22.genes.find({'p.ac': { '$in' : AC_list }}, { 'p.ac': 1 , 'pos' : 1, 'p.aid' : 1})

ac2pos = {}
for card in cards:
#	if card['p']['aid'] == 'zZ3vudw4KSmXnWHIcYz60Q':
#			print "Myxo in the house - 4808"
#			print card
#	if card['p']['aid'] == 'PUY_I8SocfrugPrZDf-i6w':
#			print "Myxo in the house - 4807"
#			print card
	ac2pos[card['p']['ac']] = card['pos']

#print ac2pos

output = ''
tags = []

seq1_sel = []
seq2_sel = []

pair_list = {}

for seq1 in seq1_list:
	try:
		print tag2ac[seq1]
		pos1 = ac2pos[tag2ac[seq1]]
	except KeyError:
		continue
	for seq2 in seq2_list:
		try:
			pos2 = ac2pos[tag2ac[seq2]]	
		except KeyError:
			continue
		if seq1.split('-')[0] == seq2.split('-')[0]:
			if '-n' in sys.argv:
				if pos1 == pos2 + 1 or pos1 == pos2 - 1:
					go = True
				else:
					go = False
			if ('-n' in sys.argv and go == True ) or '-n' not in sys.argv:
				seq = seq1.split('-')[0] + '.1'
				while seq in tags:
					N = int(seq.split('.')[-1])
					seq = '.'.join(seq.split('.')[:-1]) + '.' + str(N+1)
				tags.append(seq)				
				output += '>' + seq + '\n' + seq1_dic[seq1] + seq2_dic[seq2] + '\n'
				seq1_sel.append(seq1)
				seq2_sel.append(seq2)
				pair_list[seq] = [seq1, seq2]


outfile = open('concatbyorganism' + ext + '.fa','w')
outfile.write(output)
outfile.close()

#making a fasta file of selected sequences
output1 = ''
for seq in seq1_sel:
	output1 += '>' + seq + '\n' + seq1_dic[seq] + '\n'
with open(sys.argv[1] + '.selected' + ext + '.fa', 'w') as f:
	f.write(output1)

output2 = ''
for seq in seq2_sel:
	output2 += '>' + seq + '\n' + seq2_dic[seq] + '\n'
with open(sys.argv[2] + '.selected' + ext + '.fa', 'w') as f:
	f.write(output2)

with open('pairlist' + ext + '.json', 'w') as f:
	json.dump(pair_list, f, indent = 2)

print 'Done'

