#! /usr/bin/env python 
###################################
#    Davi Ortega 5/16/2013 
###################################
import sys
import bitk
if '-h' in sys.argv:
	print 'Just to put in my format of fasta. Option -u for update the file'
	sys.exit()

seq_dic, seq_list = bitk.fastareader(sys.argv[1])

output = ''
for tag in seq_list:
	output += '>' + tag + '\n' + seq_dic[tag] + '\n'

if '-u' in sys.argv:
	dataout = open(sys.argv[1], 'w')
	dataout.write(output)
	dataout.close()
else:
	dataout = open(sys.argv[1][:-3] + '.new.fa', 'w')
        dataout.write(output)
        dataout.close()

