#! /usr/bin/env python 
###################################
#    Davi Ortega 4/13/2014 
###################################
import sys
if '-h' in sys.argv:
	print 'put your explanation here'
	sys.exit()


datafile = open(sys.argv[1],'r')

output = ''

for line in datafile:
	if line[0] != '>':
		output += str(len(line.replace('\n',''))) + '\n'

datafile.close()

outfile = open('fa2len.results.dat' ,'w')
outfile.write(output)
outfile.close()
