#! /usr/bin/env python 
###################################
#    Davi Ortega 4/13/2014 
###################################
import sys
import bitk
import numpy
if '-h' in sys.argv:
	print 'put your explanation here'
	sys.exit()


seq_dic, tags  = bitk.fastareader(sys.argv[1])

output = ''

lenall = []
lennogaps = []

for tag in tags:
	seq = seq_dic[tag]
	output += str(len(seq)) + '\n'
	lenall.append(len(seq))
	lennogaps.append(len(seq.replace('-','')))

lenall = numpy.array(lenall)
lennogaps = numpy.array(lennogaps)
print lenall.mean()
print lennogaps.mean() 

outfile = open('fa2len.results.dat' ,'w')
outfile.write(output)
outfile.close()
