#! /usr/bin/env python 
###################################
#    Davi Ortega 9/4/2013 
###################################
import ete2
import json
import sys
import os
import bitk



if '-h' in sys.argv:
    print 'Return mistid from tree. Input yourtree.nwk'
    sys.exit()

filename = sys.argv[1]
T = ete2.Tree(filename)

output = ''
for node in T.traverse():
	if node.name != 'NoName':
		output += node.name.split('|')[0] + '\n'
			
with open(filename + '.mistid.list' , 'w') as f:
	f.write(output)

