#! /usr/bin/env python 
###################################
#    Davi Ortega 10/17/2014 
###################################
import bitk
import sys
if '-h' in sys.argv:
	print 'Input list of locus. Output fasta with sequences'
	sys.exit()

lc_list = []
feature = {}

with open(sys.argv[1], 'r') as f:
	for l in f:
		items = l.replace('\n','').split('-')
		lc_list.append(items[0])
		if len(items) > 1:
			feature[items[0]] = '-'.join(items[1:])


ac_list = bitk.lc2ac(lc_list)

ac2tag, error = bitk.accession2bitktag(ac_list)
ac2seq = bitk.accession2seq(ac_list)

output = ''
for ac in ac_list:
	if feature == {}:  
		output += '>' + ac2tag[ac] + '\n' + ac2seq[ac] + '\n'
	else:
		try:
			output += '>' + ac2tag[ac] + '-' + feature[ac] + '\n' + ac2seq[ac] + '\n'
		except KeyError:
			output += '>' + ac2tag[ac] + '\n' + ac2seq[ac] + '\n'

with open(sys.argv[1][:-3] + '.fa', 'w') as f:
	f.write(output)

print "Error"
print error
