#! /usr/bin/env python 
###################################
#    Davi Ortega 9/23/2013 
###################################
import sys
import bitk
if '-h' in sys.argv:
	print 'make a fasta format file with the sequences from the COG_finder output data. getseqfromcogoutput file.cogout.dat fastafilewithallseq.fa N1 N2 N3 \n Nx are cog numbers'
	sys.exit()

COGs = sys.argv[3:]

seq_dic, seq_list = bitk.fastareader(sys.argv[2])

output = ''

cogin = open(sys.argv[1],'r')
for line in cogin:
	if 'COG ' in line:
		if line.replace('\n','').split(' ')[1] in COGs:
			for line in cogin:
				if line != '\n':
					tag = line.replace('\n','')
					output += '>' + tag + '\n' + seq_dic[tag] + '\n'
				else:
					break

cogin.close()

dataout = open(sys.argv[1][:-3] + 'cogs.' + '.'.join(COGs) + '.fa', 'w')
dataout.write(output)
dataout.close()



