#! /usr/bin/env python 
###################################
##    Davi Ortega                ##
###################################
import bitk
import sys

if '-h' in sys.argv:
	print 'Reads tags from one alignment (or list) and keeps only those from the second alignment\n\n\tSintaxe: python keeptag list_align.fa (or .list) alignment.fa'
	sys.exit()

try:
	filel_dic, filel_list = bitk.fastareader(sys.argv[1])
except:
	filel_list = []
	dataopen = open(sys.argv[1],'r')
	for tag in dataopen:
		filel_list.append(tag.replace('\n','').replace('>',''))

orign_dic, orign_list = bitk.fastareader(sys.argv[2])

output = ''
for tag in filel_list:
	try:
		output += '>' + tag + '\n' + orign_dic[tag] + '\n'
	except IndexError:
		pass

datafile = open(sys.argv[2][:-3] + '.new.fa', 'w')
datafile.write(output)
datafile.close()
	
