#! /usr/bin/env python 
###################################
##    Davi Ortega                ##
###################################
import bitk
import sys

if '-h' in sys.argv:
	print 'Reads tags from one alignment and keeps only those from the second alignment\n\n\tSintaxe: python keeplocus.py list_align.fa alignment.fa'
	sys.exit()

filel_dic, filel_list = bitk.fastareader(sys.argv[1])
orign_dic, orign_list = bitk.fastareader(sys.argv[2])

output = ''
for tag in filel_list:
	try:
		output += '>' + tag + '\n' + orign_dic[tag] + '\n'
	except IndexError:
		pass

datafile = open(sys.argv[2][:-3] + '.new.fa', 'w')
datafile.write(output)
datafile.close()
	
