#! /usr/bin/env python 
###################################
##    Davi Ortega                ##
###################################
import bitk
import sys

if '-h' in sys.argv:
	print 'Reads tags from one alignment (or list) and keeps only those from the second alignment\n\n\tSintaxe: python keeptag alignment.fa list_align.fa (or .list)'
	sys.exit()

try:
	filel_dic, filel_list = bitk.fastareader(sys.argv[1])
except:
	filel_list = []
	dataopen = open(sys.argv[1],'r')
	for tag in dataopen:
		filel_list.append(tag.replace('\n','').replace('>',''))

orign_dic, orign_list = bitk.fastareader(sys.argv[2])

output = ''
for oldtag in filel_list:
	tag = '-'.join(oldtag.split('-')[:3])
	try:
		output += '>' + oldtag + '\n' + orign_dic[tag] + '\n'
		print oldtag
	except KeyError:
		print "\033[91m" + oldtag + '\033[0m'
		pass

datafile = open(sys.argv[1][:-3] + '.new.fa', 'w')
datafile.write(output)
datafile.close()
	
