#! /usr/bin/env python 
###################################
#    Davi Ortega 12/31/2015 
###################################
import sys
import bitk
if '-h' in sys.argv:
	print 'return the length of the largest sequence in the fasta file.\n \
            Sintax: len4fasta fastafile.fa '
	sys.exit()

seq_dic, seq_list = bitk.fastareader(sys.argv[1], "w")

maxlen = 0
for seq in seq_list:
    L = len(seq_dic[seq])
    if L > maxlen:
        maxlen = L

print maxlen
