#! /usr/bin/env python
###################################
#    Davi Ortega 1/30/2014 
###################################
import sys
import bitk
if '-h' in sys.argv:
        print 'Mist id to strain: just list of mist_id and output is the mist_id [tab] strain name'
        sys.exit()

mist = bitk.get_mist22_client()


output = ''

datafile = open(sys.argv[1],'r')
for line in datafile:
        mist_id = line.replace('\n','')
        res = mist.genomes.find_one({"_id":int(mist_id)}, {"n":1})
        if res != None:
                output += str(res['_id']) + '\t' + res['n'] + '\n'
        else:		
		output += mist_id + '\n'
		print mist_id
		sys.exit()
datafile.close()

datafile = open(sys.argv[1][:-3]+ '.strain.list','w')
datafile.write(output)
datafile.close()
