#! /usr/bin/env python 
###################################
#    Davi Ortega 9/8/2014 
###################################
import sys
import bitk
if '-h' in sys.argv:
	print 'Reads a list of mistid and outputs a list of refseq project id'
	sys.exit()

genomes = []
with open(sys.argv[1], 'r') as f:
	for line in f:
		genomes.append(int(line.replace('\n','')))
	
mist = bitk.get_mist22_client()

data = mist.genomes.find({'_id' : { '$in' : genomes }}, {'uid' : 1})

output = ''
for d in data:
	output += str(d['uid']) + '\n'

with open('refseq.list', 'w') as f:
	f.write(output)

