#! /usr/bin/env python 
###################################
#    Davi Ortega 9/4/2013 
###################################
import ete2
import json
import sys
import os

if '-h' in sys.argv:
    print 'Make tree from nwk file using ete2 python module. Input yourtree.nwk \n \
    	   Options: -pdf    Generate PDF\n \
	   	    -svg    Outputs SVG\n \
		    -show   Show tree\n \
		    -bal    Balance tree\n \
		    -aln    Align leaf names\n \
		    -c      Circular layout\n \
		    -c180   Semi-circular layout\n \
		    --image N1,N2 Insert image with name in bmp. Ni are index of features that should be deleted to match image name. N1 = -1 for name in tree == name in image '
    sys.exit()

with open(sys.argv[2], 'r') as f:
	org_dic = json.load(f)


T = ete2.Tree(sys.argv[1])

ts = ete2.TreeStyle()


output = ''


for n in T.traverse():
	if n.is_leaf():
		output += n.name + '\n'
		name = n.name.replace('_',' ')
		if name in org_dic.keys():
			print name
			if name == org_dic[name][0]:
				n.name = "|" + str(org_dic[name][1]) + "|" + org_dic[name][0]
			else:
				n.name = "|" + str(org_dic[name][1]) + "|" + org_dic[name][0] + '|' + name


with open( sys.argv[1] + ".tags.dat", 'w') as f:
	f.write(output)

T.write( outfile = sys.argv[1] + '.withmistid.nwk')

