#! /usr/bin/env python 
###################################
#    Davi Ortega 1/30/2014 
###################################
import sys
import os
if '-h' in sys.argv:
	print 'this will psiblast mist, it will take all the options for blast format as usual but the db name and the query file (will be the file you provide against mist database). Mist will be in the following format: >organism_mistid-locus-accession. Sintax: psiblastmist filetobeblasted.fa N [optional flags for blast (use \\" for ")  ], N is the number of iterations '
	print 'This is the default: -num_threads 12 -outfmt "6 qseqid sseqid bitscore evalue qlen length qcovs slen" -evalue 10E-30 -max_target_seqs 100000 -num_iterations 4'
	sys.exit()

MISTDB = "/home/ortegad/MIST2.2/fasta/all/mistdb"
#os.system('ln -s /home/ortega/MIST2.2/fasta/all/mist* ./')

try:
	num_iter_psi = int(sys.argv[2])
except:
	num_iter_psi = 4

filename = sys.argv[1]
print len(sys.argv)
if len(sys.argv) == 3:
	options = '-num_threads 12 -outfmt "6 qseqid sseqid bitscore evalue qlen length qcovs slen" -evalue 10E-30 -max_target_seqs 100000 -num_iterations ' + str(num_iter_psi)
else:
	options = " ".join(sys.argv[3:])
print options

os.system('psiblast -db ' + MISTDB + ' -query ' + sys.argv[1] + ' -out ' + sys.argv[1][:-3] + '.psiblastedvsmistdb.dat ' +  options )

