#! /usr/bin/env python 
###################################
#    Davi Ortega 3/12/2012 
###################################
import sys
import fuzzy_davi
import sys
import time
import os
if '-h' in sys.argv:
	print 'Reads the data in N dimension and output euclidean distance matrix, use -sep_in "#" where # is the separator of input data and -sep_out "#" for output data. Also, use -no_header to eliminate the top line of the matrix (thi is necessary for MDS_3D). Also for MDS_3D use sep_out as default'
	sys.exit()

start = time.time()
m0 = fuzzy_davi.memory()

if '-sep_in' in sys.argv:
        sep_in = sys.argv[sys.argv.index('-sep_in') + 1]
else:
	sep_in = '\t'

if '-sep_out' in sys.argv:
        sep_out = sys.argv[sys.argv.index('-sep_out') + 1]
else:
        sep_out = ';'



names, all_coords = fuzzy_davi.read_coords(sys.argv[1], lim = sep_in)
print names
print all_coords
print "Making the distance matrix"
Dmatrix = fuzzy_davi.DistMtx(all_coords)
print Dmatrix
print "File loaded in: " + str(time.time() - start)
print "Memory load: " + str(fuzzy_davi.memory(m0))

#names.sort()
print len(Dmatrix)
print len(Dmatrix[0])
print sep_in

if '-no_header' in sys.argv:
	output = ''
else:
	output = 'sample' + sep_out + sep_out.join(names) + '\n'

for i in range(len(names)):
	output += names[i]
	for j in Dmatrix[i]:
		output += sep_out + str(j)
	output += '\n'

outfile = open(sys.argv[1][:-3] + 'Dmatrix.txt', 'w')
outfile.write(output)
outfile.close()



if '-pdf' in sys.argv:
	r_command = "D <- read.table('" + sys.argv[1][:-3] + 'Dmatrix.txt' + "', header = T, sep = '\\t')\nDM <- data.matrix(D[,2:length(D)])\nrow.names(DM) <- D$sample\npdf('"+sys.argv[1][:-3] + 'Dmatrix.pdf' + "')\nheatmap(DM, symm = T)\ndev.off()"
	rfile = open('r_script.tmp.r','w')
	rfile.write(r_command)
	rfile.close()
	os.system('R CMD BATCH r_script.tmp.r')
	os.system('rm r_script.tmp.r')

	
	




sys.exit()

if '-e' in sys.argv:
	X, X_2D = fuzzy_davi.coord2(names, Dmatrix, sys.argv[1], 'y')
else:
	X, X_2D = fuzzy_davi.coord2(names, Dmatrix, sys.argv[1])

output = ''
out = ''

old_prefix = ''
tabs = -1
frame = 0

for name in names:
	line = X_2D[name]
        output = output + name + '{'
	out += name + '\t'
#	out += '\t'*tabs*len(line)
	if name[:3] + name[9:12] != old_prefix:
		tabs += 1
		old_prefix = name[:3] + name[9:12]
		frame = 0
        for val in line:
                output = output + str(val) + ' , '
		if line[0] == val:
			out += str(val).replace('(','').replace('+0j)','') + '\t'*(tabs*(len(line))+1)
		else:
			out += str(val).replace('(','').replace('+0j)','') + '\t'
	
        output = output + '}\n'
	out += str(frame) + '\n'
	frame += 1

fileout = open(sys.argv[1][:-3] + 'coord.txt', 'w')
fileout.write(out)
fileout.close()

