#!/usr/bin/env python
import sys
from bitk import *
from os import getcwd

if '-h' in sys.argv:
	print "\n Recontruct the old taxon names to the tree.\n \
	Run the code at the directory where your dic_fa2phy.*.dat and your tree file are. The only argument needed is the name of your tree file."
	sys.exit()

filename = sys.argv[1][:-19]

dic = open( 'dic_fa2phy.' + filename + '.dat', 'r')
tree = open(sys.argv[1], 'r')

dic_aln2phy = {}

for line in dic:
	phy_name = line[:line.find(';')]
	real_name = line[line.find(';')+1:-1]
	dic_aln2phy[phy_name] = real_name

rec_taxon_tree = ''

for line in tree:
	for old_taxon in dic_aln2phy.keys():
		if old_taxon in line:
			line = line.replace(old_taxon,dic_aln2phy[old_taxon])
	rec_taxon_tree = rec_taxon_tree + line

dic.close()
tree.close()

if '.' in sys.argv[1]:
	outfile_name = sys.argv[1][:-3] + 'rec.nwk' 
else:
	outfile_name = sys.argv[1] + '_rec'


outfile = open( outfile_name, 'w')
outfile.write(rec_taxon_tree)
outfile.close()

