#!/usr/bin/env python
import sys
from bitk import *
import os

if '-h' in sys.argv:
	print "\n Recontruct the old taxon names to the tree.\n \
	Run the code at the directory where your dic_fa2phy.*.dat and your tree file are. The only argument needed is the name of your tree file."
	sys.exit()

filename = sys.argv[1][:-19]

dic = open( 'dic_fa2phy.' + filename + '.dat', 'r')

dic_aln2phy = {}

for line in dic:
	phy_name = line[:line.find(';')]
	real_name = line[line.find(';')+1:-1]
	dic_aln2phy[phy_name] = real_name.replace('(','|').replace(')','|').replace(':','|').replace(',','|').replace("'", "")

dic.close()

os.system("cp " + sys.argv[1] + " " + sys.argv[1][:-3] + 'rec.nwk')

for phy_name in dic_aln2phy.keys():
	print phy_name
	print "sed -i 's/" + phy_name + "/" + dic_aln2phy[phy_name] + "/g' " + sys.argv[1][:-3] + "rec.nwk"
	os.system("sed -i 's/" + phy_name + "/" + dic_aln2phy[phy_name] + "/g' " + sys.argv[1][:-3] + "rec.nwk")


