#! /usr/bin/env python
###################################
#    Davi Ortega 1/30/2014 
###################################
import sys
import pymongo
if '-h' in sys.argv:
        print 'Mist id to strain: just list of mist_id and output is the mist_id [tab] strain name'
        sys.exit()

try:
        client = pymongo.MongoClient('localhost',27017)
except Connection:
        print "You must open a tunnel with ares.bio.utk.edu: ssh -L 27017:are.bio.utk.edu:27017 ares.bio.utk.edu"
        sys.exit()

N = int(sys.argv[1])

mist = client.mist22

output = ''
#print mist.db.genomes.find_one()
#print mist.db.signal_genes5.find_one({'dc': {'CheW':1}})
#print 'here'

for res in mist.signal_genes5.find({'dc.CheW':N},{'_id':1}):
#	print res
	gene = mist.genes.find_one({'_id':res['_id']},{'gid':1, 'p.aid':1, 'lo':1, 'p.ac':1})
	genome = mist.genomes.find_one({'_id':gene['gid']}, {'g':1, 'sp':1})
#	print gene['p']['aid']
	seq = mist.aseqs.find_one({'_id':gene['p']['aid']}, {'s':1})
	if 'lo' not in gene.keys():
		gene['lo'] = 'NULL'

	output += '>' + genome['g'][:2] + '.' + genome['sp'][:3] + '.' + str(gene['gid']) + '-' + gene['lo'] + '-' + gene['p']['ac'] + '\n' + seq['s'] + '\n'

datafile = open('CheW.' + str(N) + '.fa','w')
datafile.write(output)
datafile.close()
