#! /usr/bin/env python 
###################################
#    Davi Ortega 10/14/2014 
###################################
import sys
import ete2
if '-h' in sys.argv:
	print 'Select trees from multi-tree file (one tree per line) and a file with the numbers of the trees to be selected'
	sys.exit()


selected = []


selection = []
with open(sys.argv[2],'r') as f:
	for line in f:
		try:
			selection.append(int(line.replace('\n','').split(' ')[0])+ 0)
		except:
			print "You failed!"
			sys.exit()

tree = []

with open(sys.argv[1], 'r') as f:
	for line in f:
		tree.append(line.replace('\n',''))

output = ''

for i in selection:
	output += tree[i] + '\n'

with open(sys.argv[1] + '.selected.nwk', 'w') as f:
	f.write(output)


