#!/usr/bin/env python
import sys
import bitk

if '-h' in sys.argv:
	print 'Sort an alignment (CLUSTAW format) according with a tree in nwk format\n\n\
		sintax: sortbytree youralignment.aln yourtree.nwk flags\n\n \
		Flags: \n \
		-name		reads just the name of the sequence no the length\n'
	sys.exit()


seq = sys.argv[1]
tree = sys.argv[2]

if '-name' in sys.argv:
	seq_dic, seq_list = bitk.fastareader(seq,just_name = 'Yes')
	tree_list = bitk.nwkreader2(tree)
else:
	seq_dic, seq_list = bitk.fastareader(seq)
	tree_list = bitk.nwkreader2(tree)

print len(tree_list)
print len(seq_list)

output = ''
for name in tree_list:
	if name in seq_list:
		output = output + '>' + name + '\n' + seq_dic[name] + '\n'
	else:
		print 'Not in the alignment: ' + name

#print seq_dic.keys()

outfile = open( seq[:-3] + '.sorted.fa', 'w')
outfile.write(output)
outfile.close()
