#!/usr/bin/env python
import sys
from bitk import *

if '-h' in sys.argv:
        print 'Sort an html SS alignment (VISSA format) according with a tree in nwk format\n\n\
	       Sintax: sortbytree youralignment.aln yourtree.nwk flags\n\n \
	       Flags: \n \
	        -name           reads just the name of the sequence no the length\n'
	sys.exit()



seq = sys.argv[1]
tree = sys.argv[2]

if '-name' in sys.argv:
        seq_dic = vissareader(seq,just_name = 'Yes')
	tree_list = nwkreader(tree,'Yes')
else:
        seq_dic = vissareader(seq)
	tree_list = nwkreader(tree)

output = '<html>\n<body>\n<pre>\n'
for name in tree_list:
	if name in seq_dic.keys():
		space = ' '*(42-len(name))
		output = output + name + space + seq_dic[name] 

output = output + '</pre>\n</body>\n</html>'

outfile = open( seq[:-3] + 'sorted.doc', 'w')
outfile.write(output)
outfile.close()

