#! /usr/bin/env python 
###################################
#    Davi Ortega 9/4/2013 
###################################
import ete2
import json
import sys
import os
import bitkTOL
import glob
import bitk

if '-h' in sys.argv:
    print 'Summary of taxonomic information. list.list N (N is the taxonomic level)'
    sys.exit()


tax_level = int(sys.argv[2])
mist22 = bitkTOL.get_mist22_client()

results = {}
files = glob.glob(str(sys.argv[1]))
alltax = {}
distinct = {}

for fname in files:
	genomes = []
	print fname
	seq_dic, tags = bitk.fastareader(fname)
	for tag in tags:
		try:
			gid = int(tag.split('-')[0].split('.')[-1])
		except ValueError:
			gid = int(tag.split("|")[0])

		genomes.append(gid)
	genomes_original = genomes
	genomes = list(set(genomes))
	print genomes	
	print str(len(genomes)) + '\t' + str(len(genomes_original))
#	with open(fname, 'r') as f:
#		for line in f:
#			genomes.append(int(line.replace('\n','')))
	cards = mist22.genomes.find({'_id' :  { '$in' : genomes }})

	tax = { 'notaxa' : [ 0, ''] }
	tax_perseq = { 'notaxa' : [0, ''] }
	for card in cards:
		if '--show-mid' in sys.argv:
			print str(card['_id']) + '|' +  card['n'] + '|' + str(card['ta'])
		if len(card['ta']) > tax_level:
			if card['ta'][tax_level] not in alltax.keys():
				distinct[card['ta'][tax_level]] = [card['_id']]
				alltax[card['ta'][tax_level]] = card['ta']
			elif card['_id'] not in distinct[card['ta'][tax_level]]:
				distinct[card['ta'][tax_level]].append(card['_id'])
			if card['ta'][tax_level] not in tax.keys():
				tax[card['ta'][tax_level]] = [ 0, card['ta'][:tax_level]]
				tax_perseq[card['ta'][tax_level]] = [ 0, card['ta'][:tax_level]]
			tax[card['ta'][tax_level]][0] += 1
			tax_perseq[card['ta'][tax_level]][0] += genomes_original.count(card['_id'])
		else:
			tax['notaxa'][0] += 1
			tax_perseq['notaxa'][0] += 1
			print card['n']
			print card['_id']

	print "\n\n\n############# Printing the results for " + fname + " ############\n"
	results[fname] = {}
	for t in tax.keys():
		print str(tax[t][1]) + '\t' + t  + '\t' + str(tax[t][0]) + '\t' + str(tax_perseq[t][0])
		results[fname][t] = tax[t]

	alltaxsum = sum([ i[0] for i in tax.values()])
	print alltaxsum

output = 'Taxonomy\tTaxonomy group\t' + '\t'.join(files) + '\tTotal(distinct)\n' 
print results.keys()
with open('taxsum.dat', 'w') as f:
	for t in alltax.keys():
		output += str(alltax[t][:tax_level]) + '\t' + t
		for fname in files:
			try:
				output += '\t' + str(results[fname][t][0])
			except KeyError:
				output += '\t0'
		output += '\t' + str(len(distinct[t])) + '\n'
		print t
		print distinct[t]
	f.write(output)

			


