#! /usr/bin/env python 
###################################
#    Davi Ortega 9/26/2014 
###################################
import sys
if '-h' in sys.argv:
	print 'exclude duplicates in mist id list'
	sys.exit()

gids = []

with open(sys.argv[1],'r') as f:
	for line in f:
		gids.append(line.replace('\n',''))

gids = set(gids)

if '-u' in sys.argv:
	filename = sys.argv[1]
else:
	filename = sys.argv[1][:-3] + '.new.list'

with open(filename, 'w') as f:
	f.write('\n'.join(gids))

