#! /usr/bin/env python 
###################################
##    Davi Ortega                ##
###################################
import sys
import bitk

if '-h' in sys.argv:
	print "Update fasta file with class information retrived from mcp-roger.hmm output file"
	print "Sintax: hmmmcpparser.py fasta_file.fa output_hmm.dat"
	print "outfile = fasta_file.new.fa"
	sys.exit()

DIFF_THRES = 50
MIN_SCORE = 100


print "Loading hmm info"
hmmfile = open(sys.argv[2],'r')
print "Done"


print "Loading fasta...."
seq_dic, seq_list = bitk.fastareader(sys.argv[1])
print "Done"

seqn_dic = {}

errout = ''

new_seq = 1

print "Parsing........"
for line in hmmfile:
	if "Query sequence" in line:
		tag = line.split(':')[1].replace(' ','').replace('\n','')
		new_seq = 0
	if ("------" in line) and (new_seq == 0):
		new_seq = 1
		mcp_class = []
		for line2 in hmmfile:
			line_info = line2.split(' ')
			while '' in line_info:
				line_info.remove('')
			try:
				mcp_class.append([line_info[0],float(line_info[1])])
			except IndexError:
				mcp_class.append(['Uncat',1])
			if len(mcp_class) == 2:
				break
		if (mcp_class[0][1] >= MIN_SCORE) and (mcp_class[0][1] - DIFF_THRES >= mcp_class[1][1]):
			try:
				seqn_dic[tag + '--' + mcp_class[0][0]] = seq_dic[tag]
				del seq_dic[tag]
				print tag + '--' + mcp_class[0][0]
			except KeyError:
				errout += tag + '\n'
				pass
		else:
			try:
				seqn_dic[tag + '--Uncat'] = seq_dic[tag]
				print tag + '--Uncat'
				del seq_dic[tag]
			except KeyError:
				errout += tag + '\n'
				pass

hmmfile.close()

print "saving it"
outfile = open(sys.argv[1][:-2] + 'class.fa', 'w')
output = ''
for tag, seq in seqn_dic.iteritems():
	output += '>' + tag + '\n' + seq + '\n'

outfile.write(output)
outfile.close()

if errout != '':
	errfile = open('hmmmcpparser.err.log', 'w')
	errfile.write(errout)
	errfile.close()


